// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1dCVlCUq6BEFO3iSCjeG7gRAnepOuXpM',
    appId: '1:357620107243:web:f3eafddb86a3e17321bbae',
    messagingSenderId: '357620107243',
    projectId: 'hotelmangment786',
    authDomain: 'hotelmangment786.firebaseapp.com',
    storageBucket: 'hotelmangment786.appspot.com',
    measurementId: 'G-E04WGW00KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfDRyd8sUL1SxL98NWDamwq5273N6dm3M',
    appId: '1:357620107243:android:ce628c6eedd591e421bbae',
    messagingSenderId: '357620107243',
    projectId: 'hotelmangment786',
    storageBucket: 'hotelmangment786.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1dCVlCUq6BEFO3iSCjeG7gRAnepOuXpM',
    appId: '1:357620107243:web:183319074c8ca11a21bbae',
    messagingSenderId: '357620107243',
    projectId: 'hotelmangment786',
    authDomain: 'hotelmangment786.firebaseapp.com',
    storageBucket: 'hotelmangment786.appspot.com',
    measurementId: 'G-P9XQ9YB71W',
  );
}
